[build]
  publish = "dist/gurpreet-portfolio/browser"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"

# Form handling
[[forms]]
  name = "contact"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200